name: DePloY
on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - "**.json"
jobs:
  UpdatePresences:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'PreMiD'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps
        run: yarn
      - name: Compile Script
        run: yarn pu:compile
      - name: Update Presences
        env:
          MONGO_IP: ${{ secrets.MONGO_IP }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: yarn pu
